#!/usr/bin/env bash
# Reproducible build for Obsidiauranite theme.css.
# Composes: Obsidianite (base) + Aura recolor overrides + Things checkbox styling.
# Re-fetch sources with: make fetch  (or the gh api calls in README).
set -euo pipefail
cd "$(dirname "$0")"

OUT=theme.css

{
cat <<'HEADER'
/** ---------------------------------------------------------------
**  Obsidiauranite  —  Obsidianite base · Aura colors · Things checkboxes
**  Personal theme by iPurpl3x. MIT. Built from three MIT sources:
**    • Base layout ...... Obsidianite       (c) 2020 Guo Xiang        github.com/bennyxguo/Obsidian-Obsidianite
**    • Checkboxes ....... Things / Minimal  (c) 2020-2021 Stephan Ango (@kepano)  github.com/colineckert/obsidian-things
**    • Color palette .... Aura              (c) 2023 possibly matt / daltonmenezes  github.com/possibly-not/obsidian-aura-theme
**  Generated by build.sh — edit the OVERRIDE block below, not this note.
** --------------------------------------------------------------- */

HEADER

# 1) Obsidianite base (unchanged, keeps its own header + copyright)
cat _obsidianite.css

# 2) Aura recolor — override AFTER the base so it wins on equal specificity.
cat <<'OVERRIDE'

/** ===============================================================
**  OBSIDIAURANITE OVERRIDES — Aura palette on the Obsidianite base
**  Only semantic vars are touched; the neutral --color-base-* ramp is
**  left alone (hueing it is what broke contrast in the old Aura theme).
** =============================================================== */
.theme-dark,
body.theme-dark {
  /* Backgrounds — Aura near-black */
  --background-primary: #15141b;
  --background-primary-alt: #110f18;
  --background-secondary: #110f18;
  --background-secondary-alt: #0d0b12;

  /* Brand accent — Aura purple, via semantic vars */
  --interactive-accent: #a277ff;
  --interactive-accent-hover: #af8aff;
  --interactive-accent-rgb: 162, 119, 255;
  --text-accent: #a277ff;
  --text-accent-hover: #af8aff;
  --text-on-accent: #15141b;
  --color-accent: #a277ff;

  /* Aura synthwave palette — drives Things' colored checkboxes + status text */
  --color-red: #ff6767;
  --color-orange: #ffca85;
  --color-yellow: #ffe585;
  --color-green: #61ffca;
  --color-cyan: #61ffca;
  --color-blue: #82aaff;
  --color-purple: #a277ff;
  --color-pink: #f694ff;

  /* Indentation guides — subtle purple */
  --indentation-guide-color: #a277ff66;
  --indentation-guide-color-active: #a277ff;

  /* Things checkbox shape */
  --checkbox-radius: 30%;
}
OVERRIDE

# 3) Things checkbox styling (vendored). Credit: Things (@colineckert) / Minimal (@kepano).
echo ""
echo "/** ==============================================================="
echo "**  THINGS CHECKBOXES — vendored from colineckert/obsidian-things"
echo "**  Original credit: Minimal theme (@kepano). MIT."
echo "** =============================================================== */"
echo ""
echo "/* Completed checkboxes */"
sed -n '532,539p' _things.css
echo ""
sed -n '896,1196p' _things.css
} > "$OUT"

echo "Built $OUT ($(wc -l < "$OUT") lines)"
