#!/usr/bin/env bash
# Reproducible build for Obsidiauranite theme.css.
# Full Obsidianite, design untouched, recolored to ONLY the Aura palette
# (palette.sed), plus Things colored checkboxes (Aura-hued).
# Re-fetch sources: make fetch
set -euo pipefail
cd "$(dirname "$0")"

OUT=theme.css

{
cat <<'HEADER'
/** ---------------------------------------------------------------
**  Obsidiauranite  —  Obsidianite, recolored to the Aura palette · Things checkboxes
**  Personal theme by iPurpl3x. MIT. Built from three MIT sources:
**    • Base + all styling . Obsidianite     (c) 2020 Guo Xiang        github.com/bennyxguo/Obsidian-Obsidianite
**    • Checkboxes ......... Things / Minimal (c) 2020-2021 Stephan Ango (@kepano)  github.com/colineckert/obsidian-things
**    • Color palette ...... Aura            (c) 2023 possibly matt / daltonmenezes  github.com/possibly-not/obsidian-aura-theme
**  Obsidianite's design is unchanged — only color VALUES are remapped (palette.sed).
**  Generated by build.sh — do not hand-edit; change palette.sed or the ADDITIONS block.
** --------------------------------------------------------------- */

HEADER

# 1) Obsidianite, fully recolored to the Aura palette (design/rules preserved).
sed -E -f palette.sed _obsidianite.css

# 2) Aura ADDITIONS — only what Obsidianite doesn't provide, for the Things
#    checkboxes. The neutral --color-base-* ramp is deliberately NOT touched.
cat <<'ADD'

/** ===============================================================
**  OBSIDIAURANITE ADDITIONS — Aura status palette for Things checkboxes
** =============================================================== */
.theme-dark,
body.theme-dark {
  --color-red: #ff6767;
  --color-orange: #ffca85;
  --color-yellow: #ffe585;
  --color-green: #61ffca;
  --color-cyan: #61ffca;
  --color-blue: #82aaff;
  --color-purple: #a277ff;
  --color-pink: #f694ff;
  --color-accent: #a277ff;
  --checkbox-radius: 30%;
  --indentation-guide-color: #a277ff66;
  --indentation-guide-color-active: #a277ff;
}
ADD

# 3) Things checkbox styling (vendored). Credit: Things (@colineckert) / Minimal (@kepano).
echo ""
echo "/** ==============================================================="
echo "**  THINGS CHECKBOXES — vendored from colineckert/obsidian-things"
echo "**  Original credit: Minimal theme (@kepano). MIT."
echo "** =============================================================== */"
echo ""
echo "/* Completed checkboxes */"
sed -n '532,539p' _things.css
echo ""
sed -n '896,1196p' _things.css
} > "$OUT"

echo "Built $OUT ($(wc -l < "$OUT") lines)"
